name: digitopia-infra

services:
  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # Initial schema/data setup
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [backend]

  # RabbitMQ broker with management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [backend]

  # User microservice
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8081
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      # user-service exposes /api/v1/users/healtz on port 8081
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/api/v1/users/healtz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [backend]

  # Organization microservice
  org-service:
    build:
      context: ./org-service
      dockerfile: Dockerfile
    container_name: org-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8082
      # inter-service call to user-service
      USER_SERVICE_URL: http://user-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      # org-service exposes /api/v1/orgs/healtz on port 8082 (adjust if different)
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/api/v1/orgs/healtz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [backend]

  # Invitation microservice
  invitation-service:
    build:
      context: ./invitation-service
      dockerfile: Dockerfile
    container_name: invitation-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8083
      # inter-service calls
      USER_SERVICE_URL: http://user-service:8081
      ORG_SERVICE_URL: http://org-service:8082
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_healthy
      org-service:
        condition: service_healthy
    healthcheck:
      # invitation-service exposes /api/v1/invitations/healtz on port 8083
      test: ["CMD-SHELL", "wget -qO- http://localhost:8083/api/v1/invitations/healtz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [backend]

networks:
  backend:

volumes:
  pgdata:
  rabbitmq_data:
