-- userdb
CREATE DATABASE userdb;
CREATE USER userdb WITH PASSWORD 'userdb';
GRANT ALL PRIVILEGES ON DATABASE userdb TO userdb;

-- orgdb
CREATE DATABASE orgdb;
CREATE USER orgdb WITH PASSWORD 'orgdb';
GRANT ALL PRIVILEGES ON DATABASE orgdb TO orgdb;

-- invdb
CREATE DATABASE invdb;
CREATE USER invdb WITH PASSWORD 'invdb';
GRANT ALL PRIVILEGES ON DATABASE invdb TO invdb;
